sudo: false
language: ruby
bundler_args: "--without development"
script:
  - cat Gemfile.lock
  - bundle list
  - bundle exec rake $CHECK
cache: bundler
matrix:
  include:
    - rvm: 2.4.3
      env: 
        - CHECK=test
        - PUPPET_VERSION='~> 5.3.0'
    - rvm: 2.4.3
      env: 
        - CHECK=test
        - PUPPET_VERSION='~> 4.9.0'
    - rvm: 2.4.3
      env: 
        - CHECK=beaker
        - PUPPET_VERSION='~> 5.3.0'
    - rvm: 2.4.3
      env:
        - CHECK=beaker
        - PUPPET_VERSION='~> 4.9.0'
