sudo: false
language: ruby
bundler_args: "--without development"
script:
  - cat Gemfile.lock
  - bundle list
  - bundle exec rake $CHECK
cache: bundler
matrix:
  include:
    - rvm: 2.4.3
      env: CHECK=spec
    - rvm: 2.4.3
      env: CHECK=rubocop
    - rvm: 2.1.9
      env: CHECK=beaker
    - rvm: 2.1.9
      env: CHECK=spec
